spring:
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/online_shop
    username: app
    password: Coo2022*
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        format_sql: true
server:
  port: 8081
  servlet:
    context-path: /order-service
